### ISSUE TITLE
ValueRestriction getList Problem

### ISSUE THREAD

**Issue by karamanmehmet** [danjee/generic-data#10]
Dear developers,

I am using your framework which is very flexible and make me faster. Thanks for it;

But I couldnt implement ValueRestriction list . While calling getList method I get "The method getList(Class<T>, QueryParameter, T) in the type GenericService is not applicable for the arguments (Class<Irsaliye>, String, List<ValueRestriction>)" error

	@Autowired
	private GenericService service;

	public List<News> findAllByFirma(Firma firma, Sube sube) {
		
		List<ValueRestriction> restrictions = new ArrayList<>();

		if(firma!=null)
			restrictions.add(new ValueRestriction("firma", QueryParameter.EQ, firma));
		
		if(sube!=null)
			restrictions.add(new ValueRestriction("sube", QueryParameter.EQ, sube));
		
		return service.getList(News.class, QueryParameter.OR_RESTRICTIONS, restrictions);

	}

Where am I wrong?

**Comment by danjee** [comment]
You can use something like this:

```java
public List<News> findAllByFirma(Firma firma, Sube sube) {
		
		List<ValueRestriction> restrictions = new ArrayList<ValueRestriction>();

		if(firma!=null)
			restrictions.add(new ValueRestriction("firma", QueryParameter.EQ, firma));
		
		if(sube!=null)
			restrictions.add(new ValueRestriction("sube", QueryParameter.EQ, sube));
	
		
		ValueRestriction vor = new ValueRestriction();
		vor.setOrRestrictions(restrictions);
		
		return service.getList(News.class, QueryParameter.build().addRestriction(vor));

	}
```

**Comment by karamanmehmet** [comment]
Thanks for all
