### ISSUE TITLE
Implementing Limit Clause

### ISSUE THREAD

**Issue by karamanmehmet** [danjee/generic-data#11]
Dear Danjee,

I am wondering how can I implement latest N record with generic_service;

For example I have User class and it related with the company entity. I want to get latest N User as a List 

Select * from Users where company_id=10 order by id desc Limit 10;

Thanks

**Comment by danjee** [comment]
You can use QueryParameter methods orderBy and setFirst​ with setCount chained together.

**Comment by karamanmehmet** [comment]
Thanks for all
