### ISSUE TITLE
How Can Reach Foreing Key Related Entity

### ISSUE THREAD

**Issue by karamanmehmet** [danjee/generic-data#12]
In my project I have two entities ;
 InvoiceEntity( id , groupcode, company, currencytype)
CompanyEntity(id, name,code,workfield);

I generate QP as follows;		

QueryParameter qp=new QueryParameter();

qp.addRestriction(new ValueRestriction("groupcode", EQ, groupcode));
qp.addRestriction(new ValueRestriction("company.code", EQ, code));

List<InvoiceEntity> list= service.getList(InvoiceEntity.class,qp.addLazyFieldToInitialize("currencytype").addLazyFieldToInitialize("company"));

When run the code ;
I get this error. How Can I implement "Alias" with project
org.hibernate.QueryException: could not resolve property: company.code of: edu.anatolia.InvoiceEntity

Thanks for all

**Comment by danjee** [comment]
At the moment you cannot use alias as you will do with bare hibernate.

**Comment by karamanmehmet** [comment]
Thanks for quick answer
