### ISSUE TITLE
It doesn't work when I follow the readme file...

### ISSUE THREAD

**Issue by lanluobo** [danjee/generic-data#4]
It says that we can use from Maven central
`<dependency>
    <groupId>ro.fortsoft</groupId>
    <artifactId>generic-data</artifactId>
    <version>1.9.0</version>
</dependency>`
but when I do so,the jar can't be downloaded to my project. I change "generic-data" to "generic-data-service",and then it works.
something wrong with me? or something wrong with the readme file?

**Comment by danjee** [comment]
I will review the readme file, the generic-data is the parent pom.
Thank you
