### ISSUE TITLE
More sample Code

### ISSUE THREAD

**Issue by karamanmehmet** [danjee/generic-data#6]
Dear developers,

Any help or sample code demo for generic-data project ?
If you have could you send ?

Thanks for all

**Comment by danjee** [comment]
Hello,
Thanks for your interest on the project.
Yes, I can provide more sample code in the README.MD or even a demo folder the repo. I will add them in the next days.

**Comment by karamanmehmet** [comment]
Thansk Danjee it will be so good for me. By the your codes are awesome

**Comment by danjee** [comment]
Hello @karamanmehmet 
I've added some examples with the [`PR`](https://github.com/danjee/generic-data/pull/7)
Please check them and if it's OK for you I can merge them to master. These examples do not cover all of the GenericService and GenericDAO functionalities but can give you an idea on how to use them. 
Thank you

**Comment by karamanmehmet** [comment]
Hi @danjee its ok for me . Thank you so much for your consideration.
